version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cinetix-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: login-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: cinetix-core-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
